M48
; DRILL file {KiCad 6.0.1-79c1e3a40b~116~ubuntu21.04.1} date Tue 15 Feb 2022 04:14:26 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-02-15T16:14:26-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.1-79c1e3a40b~116~ubuntu21.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C6.500
%
G90
G05
T1
X111.716Y-116.462
X116.116Y-116.462
T2
X60.5Y-39.0
X115.5Y-39.0
T3
X87.63Y-39.116
T0
M30
